-- Pisa Fundo championship schema
--
-- This migration is intentionally safe to apply to the database originally
-- created by Django: existing tables and rows are preserved. On a fresh
-- Supabase project it creates the same public schema expected by the Next.js
-- application.

begin;

create table if not exists public.championship_season (
  id bigint generated by default as identity,
  name varchar(100) not null,
  year integer not null,
  is_active boolean not null default false,
  constraint championship_season_pkey primary key (id),
  constraint championship_season_year_check check (year >= 0)
);

create table if not exists public.championship_team (
  id bigint generated by default as identity,
  name varchar(100) not null,
  slug varchar(120) not null,
  primary_color varchar(7) not null,
  secondary_color varchar(7) not null,
  constraint championship_team_pkey primary key (id),
  constraint championship_team_name_key unique (name),
  constraint championship_team_slug_key unique (slug)
);

create table if not exists public.championship_driver (
  id bigint generated by default as identity,
  name varchar(100) not null,
  nickname varchar(50) not null default '',
  slug varchar(120) not null,
  number integer,
  constraint championship_driver_pkey primary key (id),
  constraint championship_driver_slug_key unique (slug),
  constraint championship_driver_number_check check (number >= 0)
);

create table if not exists public.championship_driverteamseason (
  id bigint generated by default as identity,
  car_number integer,
  driver_id bigint not null,
  season_id bigint not null,
  team_id bigint not null,
  is_guest boolean not null default false,
  constraint championship_driverteamseason_pkey primary key (id),
  constraint championship_driverteamseason_car_number_check check (car_number >= 0),
  constraint championship_driverteamseason_season_driver_key unique (season_id, driver_id),
  constraint championship_driverteamseason_driver_fkey
    foreign key (driver_id) references public.championship_driver(id)
    deferrable initially deferred,
  constraint championship_driverteamseason_season_fkey
    foreign key (season_id) references public.championship_season(id)
    deferrable initially deferred,
  constraint championship_driverteamseason_team_fkey
    foreign key (team_id) references public.championship_team(id)
    deferrable initially deferred
);

create table if not exists public.championship_round (
  id bigint generated by default as identity,
  name varchar(100) not null,
  date date not null,
  location varchar(100) not null,
  "order" integer not null,
  season_id bigint not null,
  constraint championship_round_pkey primary key (id),
  constraint championship_round_order_check check ("order" >= 0),
  constraint championship_round_season_order_key unique (season_id, "order"),
  constraint championship_round_season_fkey
    foreign key (season_id) references public.championship_season(id)
    deferrable initially deferred
);

create table if not exists public.championship_roundresult (
  id bigint generated by default as identity,
  position integer not null,
  fastest_lap boolean not null default false,
  points integer not null default 0,
  entry_id bigint not null,
  round_id bigint not null,
  has_penalty boolean not null default false,
  penalty_reason varchar(200) not null default '',
  status varchar(10) not null default 'COMPLETED',
  constraint championship_roundresult_pkey primary key (id),
  constraint championship_roundresult_position_check check (position >= 0),
  constraint championship_roundresult_points_check check (points >= 0),
  constraint championship_roundresult_entry_fkey
    foreign key (entry_id) references public.championship_driverteamseason(id)
    deferrable initially deferred,
  constraint championship_roundresult_round_fkey
    foreign key (round_id) references public.championship_round(id)
    deferrable initially deferred
);

-- Defaults are added to the legacy Django tables as well. These changes do
-- not rewrite existing rows and make manual entry in Supabase less error-prone.
alter table public.championship_season
  alter column is_active set default false;
alter table public.championship_driver
  alter column nickname set default '';
alter table public.championship_driverteamseason
  alter column is_guest set default false;
alter table public.championship_roundresult
  alter column fastest_lap set default false,
  alter column points set default 0,
  alter column has_penalty set default false,
  alter column penalty_reason set default '',
  alter column status set default 'COMPLETED';

-- Constraints that were previously enforced only by Django model validation.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'championship_roundresult_status_check'
      and conrelid = 'public.championship_roundresult'::regclass
  ) then
    alter table public.championship_roundresult
      add constraint championship_roundresult_status_check
      check (status in ('COMPLETED', 'DNF', 'DNS'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'championship_roundresult_position_positive_check'
      and conrelid = 'public.championship_roundresult'::regclass
  ) then
    alter table public.championship_roundresult
      add constraint championship_roundresult_position_positive_check
      check (position >= 1);
  end if;
end;
$$;

create unique index if not exists championship_roundresult_round_entry_uniq
  on public.championship_roundresult (round_id, entry_id);

create unique index if not exists championship_roundresult_round_position_uniq
  on public.championship_roundresult (round_id, position)
  where status <> 'DNS';

create unique index if not exists championship_roundresult_fastest_lap_uniq
  on public.championship_roundresult (round_id)
  where fastest_lap;

create index if not exists championship_driverteamseason_driver_id_b28325ca
  on public.championship_driverteamseason (driver_id);
create index if not exists championship_driverteamseason_season_id_ef1c16ba
  on public.championship_driverteamseason (season_id);
create index if not exists championship_driverteamseason_team_id_ea4e5347
  on public.championship_driverteamseason (team_id);
create index if not exists championship_round_season_id_937b125e
  on public.championship_round (season_id);
create index if not exists championship_roundresult_entry_id_199e292f
  on public.championship_roundresult (entry_id);
create index if not exists championship_roundresult_round_id_af6242c0
  on public.championship_roundresult (round_id);

-- Keep the stored points in sync with lib/scoring.ts, including entries made
-- directly through the Supabase Table Editor.
create or replace function public.set_roundresult_points()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  season_year integer;
  base_points integer := 0;
begin
  if new.status in ('DNF', 'DNS') then
    new.points := 0;
    return new;
  end if;

  select season.year
    into season_year
  from public.championship_round as round
  join public.championship_season as season on season.id = round.season_id
  where round.id = new.round_id;

  if season_year is null then
    raise exception 'Etapa % nao pertence a uma temporada valida.', new.round_id;
  end if;

  if season_year = 2025 then
    base_points := case new.position
      when 1 then 25 when 2 then 18 when 3 then 15 when 4 then 12
      when 5 then 10 when 6 then 8 when 7 then 6 when 8 then 4
      when 9 then 2 when 10 then 1 else 0
    end;
  else
    base_points := case new.position
      when 1 then 18 when 2 then 15 when 3 then 13 when 4 then 11
      when 5 then 9 when 6 then 7 when 7 then 5 when 8 then 3
      when 9 then 2 when 10 then 1 else 0
    end;
  end if;

  new.points := base_points + case when new.fastest_lap then 1 else 0 end;
  return new;
end;
$$;

drop trigger if exists set_roundresult_points_before_write
  on public.championship_roundresult;
create trigger set_roundresult_points_before_write
before insert or update of position, fastest_lap, status, round_id
on public.championship_roundresult
for each row execute function public.set_roundresult_points();

-- Preserve the original rule: at most two drivers per team in each season.
create or replace function public.enforce_team_driver_limit()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_driver_count integer;
begin
  select count(*)::integer
    into current_driver_count
  from public.championship_driverteamseason
  where season_id = new.season_id
    and team_id = new.team_id
    and id <> coalesce(new.id, 0);

  if current_driver_count >= 2 then
    raise exception 'Esta equipe ja tem 2 pilotos nesta temporada.';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_team_driver_limit_before_write
  on public.championship_driverteamseason;
create trigger enforce_team_driver_limit_before_write
before insert or update of season_id, team_id
on public.championship_driverteamseason
for each row execute function public.enforce_team_driver_limit();

-- Public application access is intentionally read-only. Dashboard, direct
-- Postgres connections and service_role remain available for administration.
grant usage on schema public to anon, authenticated, service_role;

revoke all on table
  public.championship_season,
  public.championship_team,
  public.championship_driver,
  public.championship_driverteamseason,
  public.championship_round,
  public.championship_roundresult
from anon, authenticated;

grant select on table
  public.championship_season,
  public.championship_team,
  public.championship_driver,
  public.championship_driverteamseason,
  public.championship_round,
  public.championship_roundresult
to anon, authenticated;

grant all privileges on table
  public.championship_season,
  public.championship_team,
  public.championship_driver,
  public.championship_driverteamseason,
  public.championship_round,
  public.championship_roundresult
to service_role;

revoke all on all sequences in schema public from anon, authenticated;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.set_roundresult_points() from public, anon, authenticated;
revoke all on function public.enforce_team_driver_limit() from public, anon, authenticated;
grant execute on function public.set_roundresult_points() to service_role;
grant execute on function public.enforce_team_driver_limit() to service_role;

alter table public.championship_season enable row level security;
alter table public.championship_team enable row level security;
alter table public.championship_driver enable row level security;
alter table public.championship_driverteamseason enable row level security;
alter table public.championship_round enable row level security;
alter table public.championship_roundresult enable row level security;

create policy "Public seasons are readable"
  on public.championship_season for select
  to anon, authenticated using (true);
create policy "Public teams are readable"
  on public.championship_team for select
  to anon, authenticated using (true);
create policy "Public drivers are readable"
  on public.championship_driver for select
  to anon, authenticated using (true);
create policy "Public entries are readable"
  on public.championship_driverteamseason for select
  to anon, authenticated using (true);
create policy "Public rounds are readable"
  on public.championship_round for select
  to anon, authenticated using (true);
create policy "Public results are readable"
  on public.championship_roundresult for select
  to anon, authenticated using (true);

-- Django's auth/session tables are not part of the public website API. Lock
-- them down if they exist in a database migrated from the legacy application.
do $$
declare
  internal_table record;
begin
  for internal_table in
    select schemaname, tablename
    from pg_tables
    where schemaname = 'public'
      and tablename ~ '^(auth|django)_'
  loop
    execute format('revoke all on table %I.%I from anon, authenticated', internal_table.schemaname, internal_table.tablename);
    execute format('alter table %I.%I enable row level security', internal_table.schemaname, internal_table.tablename);
  end loop;
end;
$$;

alter default privileges for role postgres in schema public
  revoke select, insert, update, delete, truncate, references, trigger
  on tables from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke usage, select, update on sequences from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated;
alter default privileges for role postgres in schema public
  grant select, insert, update, delete, truncate, references, trigger
  on tables to service_role;
alter default privileges for role postgres in schema public
  grant usage, select, update on sequences to service_role;

notify pgrst, 'reload schema';

commit;
