-- Additive Mini Copa model. Official seasons, rounds, entries and results remain
-- the sole source of race positions and points.

begin;

create table public.championship_cup (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.championship_season(id),
  name varchar(100) not null,
  published_at timestamptz,
  is_enabled boolean not null default false,
  created_at timestamptz not null default now()
);

create index championship_cup_season_id_idx
  on public.championship_cup (season_id);

create table public.championship_cup_round (
  cup_id bigint not null references public.championship_cup(id),
  round_id bigint not null references public.championship_round(id),
  cup_order smallint not null check (cup_order between 1 and 4),
  registration_closed_at timestamptz,
  primary key (cup_id, round_id),
  unique (cup_id, cup_order)
);

create index championship_cup_round_round_id_idx
  on public.championship_cup_round (round_id);

create table public.championship_cup_entry (
  cup_id bigint not null,
  entry_id bigint not null references public.championship_driverteamseason(id),
  first_round_id bigint not null,
  enrolled_at timestamptz not null default now(),
  enrolled_by uuid references auth.users(id) on delete set null,
  primary key (cup_id, entry_id),
  foreign key (cup_id, first_round_id)
    references public.championship_cup_round(cup_id, round_id)
);

create index championship_cup_entry_entry_id_idx
  on public.championship_cup_entry (entry_id);
create index championship_cup_entry_first_round_idx
  on public.championship_cup_entry (cup_id, first_round_id);

-- A round can only be selected prospectively and from the cup's source season.
-- Once closed, its selection and order cannot silently change the standings.
create function public.validate_championship_cup_round()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  cup_season_id bigint;
  round_season_id bigint;
begin
  if tg_op = 'DELETE' then
    if exists (
      select 1 from public.championship_cup
      where id = old.cup_id and published_at is not null
    ) then
      raise exception 'Uma etapa de Copa publicada exige correcao administrativa excepcional.'
        using errcode = '22023';
    end if;
    perform 1 from public.championship_round
    where id = old.round_id for update;
    if old.registration_closed_at is not null
      or exists (
        select 1 from public.championship_roundresult
        where round_id = old.round_id
      ) then
      raise exception 'Uma etapa da Copa encerrada ou com resultados nao pode ser removida.'
        using errcode = '22023';
    end if;
    return old;
  end if;

  if tg_op = 'UPDATE' then
    if (new.cup_id, new.round_id, new.cup_order)
      is distinct from (old.cup_id, old.round_id, old.cup_order) then
      raise exception 'O vinculo e a ordem da etapa da Copa sao imutaveis.'
        using errcode = '22023';
    end if;
    if old.registration_closed_at is not null
      and new.registration_closed_at is distinct from old.registration_closed_at then
      raise exception 'As adesoes desta etapa ja foram encerradas.'
        using errcode = '22023';
    end if;
  end if;

  select season_id into cup_season_id
  from public.championship_cup where id = new.cup_id;
  select season_id into round_season_id
  from public.championship_round where id = new.round_id for update;

  if cup_season_id is null or round_season_id is null
    or cup_season_id <> round_season_id then
    raise exception 'A etapa deve pertencer ao campeonato oficial da Copa.'
      using errcode = '22023';
  end if;

  if (tg_op = 'INSERT'
      or (tg_op = 'UPDATE' and old.registration_closed_at is null))
    and exists (
      select 1 from public.championship_roundresult
      where round_id = new.round_id
    ) then
    raise exception 'Uma etapa com resultados publicados nao pode ser incluida ou encerrada na Copa.'
      using errcode = '22023';
  end if;

  if tg_op = 'UPDATE' and old.registration_closed_at is null
    and new.registration_closed_at is not null then
    new.registration_closed_at := now();
  end if;

  return new;
end;
$$;

create trigger validate_championship_cup_round_before_write
before insert or update or delete on public.championship_cup_round
for each row execute function public.validate_championship_cup_round();

-- Joining is optional, unique per cup, never retroactive, and must happen
-- before the participant's first eligible round is closed or published.
create function public.validate_championship_cup_entry()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  cup_season_id bigint;
  entry_season_id bigint;
  entry_is_guest boolean;
  first_round_closed_at timestamptz;
begin
  if tg_op = 'UPDATE' then
    raise exception 'Adesoes nao podem ser alteradas; corrija antes do encerramento da etapa.'
      using errcode = '22023';
  end if;

  if tg_op = 'DELETE' then
    select registration_closed_at into first_round_closed_at
    from public.championship_cup_round
    where cup_id = old.cup_id and round_id = old.first_round_id
    for update;
    perform 1 from public.championship_round
    where id = old.first_round_id for update;
    if first_round_closed_at is not null
      or exists (
        select 1 from public.championship_roundresult
        where round_id = old.first_round_id
      ) then
      raise exception 'Uma adesao com etapa iniciada nao pode ser removida.'
        using errcode = '22023';
    end if;
    return old;
  end if;

  select season_id into cup_season_id
  from public.championship_cup where id = new.cup_id;
  select season_id, is_guest into entry_season_id, entry_is_guest
  from public.championship_driverteamseason where id = new.entry_id;
  select registration_closed_at into first_round_closed_at
  from public.championship_cup_round
  where cup_id = new.cup_id and round_id = new.first_round_id
  for update;
  if not found then
    raise exception 'A primeira etapa da adesao nao pertence a esta Copa.'
      using errcode = '22023';
  end if;
  perform 1 from public.championship_round
  where id = new.first_round_id for update;

  if cup_season_id is null or entry_season_id is null
    or cup_season_id <> entry_season_id or entry_is_guest then
    raise exception 'A Copa aceita apenas pilotos regulares do campeonato de origem.'
      using errcode = '22023';
  end if;
  if first_round_closed_at is not null
    or exists (
      select 1 from public.championship_roundresult
      where round_id = new.first_round_id
    ) then
    raise exception 'As adesoes desta etapa ja foram encerradas.'
      using errcode = '22023';
  end if;

  new.enrolled_at := now();
  new.enrolled_by := auth.uid();
  return new;
end;
$$;

create trigger validate_championship_cup_entry_before_write
before insert or update or delete on public.championship_cup_entry
for each row execute function public.validate_championship_cup_entry();

-- Once the cup has started, changing the identity or guest status of an
-- enrolled official entry could rewrite historical eligibility.
create function public.protect_started_cup_entry_identity()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if (new.driver_id, new.is_guest)
    is not distinct from (old.driver_id, old.is_guest) then
    return new;
  end if;

  if exists (
    select 1
    from public.championship_cup_entry cup_entry
    join public.championship_cup_round cup_round
      on cup_round.cup_id = cup_entry.cup_id
    where cup_entry.entry_id = old.id
      and (
        cup_round.registration_closed_at is not null
        or exists (
          select 1 from public.championship_roundresult result
          where result.round_id = cup_round.round_id
        )
      )
  ) then
    raise exception 'A identidade e a condicao de convidado nao podem mudar depois do inicio da Copa.'
      using errcode = '22023';
  end if;

  return new;
end;
$$;

create trigger protect_started_cup_entry_identity_before_update
before update of driver_id, is_guest on public.championship_driverteamseason
for each row execute function public.protect_started_cup_entry_identity();

-- Publication is separate from migration and may happen with fewer than four
-- linked rounds while the remaining official rounds are being scheduled.
create function public.validate_championship_cup_publication()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    if old.published_at is not null then
      raise exception 'Uma Copa publicada nao pode ser removida.'
        using errcode = '22023';
    end if;
    return old;
  end if;
  if tg_op = 'INSERT' then
    if new.published_at is not null or new.is_enabled then
      raise exception 'Cadastre as etapas antes de publicar a Copa.'
        using errcode = '22023';
    end if;
    return new;
  end if;
  if new.season_id <> old.season_id then
    raise exception 'O campeonato de origem da Copa nao pode ser alterado.'
      using errcode = '22023';
  end if;
  if old.published_at is not null
    and new.published_at is distinct from old.published_at then
    raise exception 'A data original de publicacao da Copa nao pode ser alterada.'
      using errcode = '22023';
  end if;
  if new.is_enabled and new.published_at is null then
    raise exception 'Publique a Copa antes de torna-la visivel.'
      using errcode = '22023';
  end if;
  if new.is_enabled and not exists (
    select 1 from public.championship_cup_round where cup_id = new.id
  ) then
    raise exception 'Cadastre ao menos uma etapa antes de ativar a Copa.'
      using errcode = '22023';
  end if;
  if new.published_at is not null and old.published_at is null
    and not exists (
      select 1 from public.championship_cup_round where cup_id = new.id
    ) then
    raise exception 'Cadastre ao menos uma etapa antes de publicar a Copa.'
      using errcode = '22023';
  end if;
  if new.published_at is not null and old.published_at is null then
    new.published_at := now();
  end if;
  return new;
end;
$$;

create trigger validate_championship_cup_publication_before_write
before insert or update or delete on public.championship_cup
for each row execute function public.validate_championship_cup_publication();

alter table public.championship_cup enable row level security;
alter table public.championship_cup_round enable row level security;
alter table public.championship_cup_entry enable row level security;

-- Explicit grants are required on projects that do not auto-expose SQL tables.
revoke all on table
  public.championship_cup,
  public.championship_cup_round,
  public.championship_cup_entry
from anon, authenticated;
grant select on table
  public.championship_cup,
  public.championship_cup_round,
  public.championship_cup_entry
to anon;
grant select, insert, update, delete on table
  public.championship_cup,
  public.championship_cup_round
to authenticated;
grant select, insert, delete on table
  public.championship_cup_entry
to authenticated;
grant all privileges on table
  public.championship_cup,
  public.championship_cup_round,
  public.championship_cup_entry
to service_role;
grant usage, select on sequence public.championship_cup_id_seq
  to authenticated, service_role;

create policy "Published cups are readable to visitors"
  on public.championship_cup for select
  to anon
  using (published_at is not null and is_enabled);
create policy "Published cups or admins are readable"
  on public.championship_cup for select
  to authenticated
  using (
    (published_at is not null and is_enabled)
    or exists (
      select 1 from public.app_admins where user_id = (select auth.uid())
    )
  );
create policy "Published cups or admins can read rounds"
  on public.championship_cup_round for select
  to anon, authenticated
  using (
    exists (select 1 from public.championship_cup where id = cup_id)
  );
create policy "Published cups or admins can read entries"
  on public.championship_cup_entry for select
  to anon, authenticated
  using (
    exists (select 1 from public.championship_cup where id = cup_id)
  );

create policy "Admins can insert cups"
  on public.championship_cup for insert to authenticated
  with check (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ));
create policy "Admins can update cups"
  on public.championship_cup for update to authenticated
  using (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ));
create policy "Admins can delete cups"
  on public.championship_cup for delete to authenticated
  using (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ));

create policy "Admins can insert cup rounds"
  on public.championship_cup_round for insert to authenticated
  with check (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ));
create policy "Admins can update cup rounds"
  on public.championship_cup_round for update to authenticated
  using (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ));
create policy "Admins can delete cup rounds"
  on public.championship_cup_round for delete to authenticated
  using (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ));

create policy "Admins can insert cup entries"
  on public.championship_cup_entry for insert to authenticated
  with check (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ));
create policy "Admins can delete cup entries"
  on public.championship_cup_entry for delete to authenticated
  using (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ));

revoke all on function
  public.validate_championship_cup_round(),
  public.validate_championship_cup_entry(),
  public.protect_started_cup_entry_identity(),
  public.validate_championship_cup_publication()
from public, anon, authenticated;
grant execute on function
  public.validate_championship_cup_round(),
  public.validate_championship_cup_entry(),
  public.protect_started_cup_entry_identity(),
  public.validate_championship_cup_publication()
to authenticated, service_role;

notify pgrst, 'reload schema';

commit;
