-- Controlled backfill for a Cup round whose official results already exist.
-- Official rounds and results remain read-only inputs to the Cup.

begin;

alter table public.championship_cup_round
  add column retroactive_at timestamptz,
  add column retroactive_by uuid references auth.users(id) on delete set null,
  add column retroactive_reason varchar(300),
  add constraint championship_cup_round_retroactive_metadata_check check (
    (
      retroactive_at is null
      and retroactive_by is null
      and retroactive_reason is null
    )
    or (
      retroactive_at is not null
      and length(btrim(retroactive_reason)) between 10 and 300
    )
  );

create table public.championship_cup_audit (
  id bigint generated by default as identity primary key,
  cup_id bigint not null references public.championship_cup(id),
  round_id bigint not null references public.championship_round(id),
  action varchar(40) not null check (
    action in ('RETROACTIVE_ROUND_ADDED', 'RETROACTIVE_ROUND_REMOVED')
  ),
  reason varchar(300) not null check (length(btrim(reason)) between 10 and 300),
  actor_id uuid references auth.users(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index championship_cup_audit_cup_created_idx
  on public.championship_cup_audit (cup_id, created_at desc);

alter table public.championship_cup_audit enable row level security;

revoke all on table public.championship_cup_audit from anon, authenticated;
grant select, insert on table public.championship_cup_audit to authenticated;
grant all privileges on table public.championship_cup_audit to service_role;
grant usage, select on sequence public.championship_cup_audit_id_seq
  to authenticated, service_role;

create policy "Admins can read Cup audit"
  on public.championship_cup_audit for select
  to authenticated
  using (exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  ));

create policy "Admins can append Cup audit"
  on public.championship_cup_audit for insert
  to authenticated
  with check (
    actor_id = (select auth.uid())
    and exists (
      select 1 from public.app_admins where user_id = (select auth.uid())
    )
  );

create or replace function public.validate_championship_cup_round()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  cup_season_id bigint;
  cup_published_at timestamptz;
  round_season_id bigint;
  retroactive_operation boolean :=
    coalesce(current_setting('app.cup_retroactive_operation', true), '') = 'on';
begin
  if tg_op = 'DELETE' then
    select published_at into cup_published_at
    from public.championship_cup where id = old.cup_id;

    if cup_published_at is not null then
      raise exception 'Uma etapa de Copa publicada exige correcao administrativa excepcional.'
        using errcode = '22023';
    end if;

    perform 1 from public.championship_round
    where id = old.round_id for update;

    if (
      old.registration_closed_at is not null
      or exists (
        select 1 from public.championship_roundresult
        where round_id = old.round_id
      )
    ) and not (retroactive_operation and old.retroactive_at is not null) then
      raise exception 'Uma etapa da Copa encerrada ou com resultados nao pode ser removida.'
        using errcode = '22023';
    end if;

    return old;
  end if;

  if tg_op = 'UPDATE' then
    if (new.cup_id, new.round_id, new.cup_order)
      is distinct from (old.cup_id, old.round_id, old.cup_order) then
      raise exception 'O vinculo e a ordem da etapa da Copa sao imutaveis.'
        using errcode = '22023';
    end if;
    if (new.retroactive_at, new.retroactive_by, new.retroactive_reason)
      is distinct from (old.retroactive_at, old.retroactive_by, old.retroactive_reason) then
      raise exception 'Os dados da inclusao retroativa sao imutaveis.'
        using errcode = '22023';
    end if;
    if old.registration_closed_at is not null
      and new.registration_closed_at is distinct from old.registration_closed_at then
      raise exception 'As adesoes desta etapa ja foram encerradas.'
        using errcode = '22023';
    end if;
  end if;

  select season_id, published_at into cup_season_id, cup_published_at
  from public.championship_cup where id = new.cup_id;
  select season_id into round_season_id
  from public.championship_round where id = new.round_id for update;

  if cup_season_id is null or round_season_id is null
    or cup_season_id <> round_season_id then
    raise exception 'A etapa deve pertencer ao campeonato oficial da Copa.'
      using errcode = '22023';
  end if;

  if new.retroactive_at is not null and (
    not retroactive_operation
    or cup_published_at is not null
    or new.registration_closed_at is null
  ) then
    raise exception 'Use o fluxo controlado para incluir uma etapa ja realizada.'
      using errcode = '22023';
  end if;

  if (tg_op = 'INSERT'
      or (tg_op = 'UPDATE' and old.registration_closed_at is null))
    and exists (
      select 1 from public.championship_roundresult
      where round_id = new.round_id
    )
    and not (
      retroactive_operation
      and new.retroactive_at is not null
      and cup_published_at is null
      and new.registration_closed_at is not null
    ) then
    raise exception 'Uma etapa com resultados publicados so pode ser incluida pelo fluxo retroativo.'
      using errcode = '22023';
  end if;

  if tg_op = 'UPDATE' and old.registration_closed_at is null
    and new.registration_closed_at is not null then
    new.registration_closed_at := now();
  end if;

  return new;
end;
$$;

create or replace function public.validate_championship_cup_entry()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  cup_season_id bigint;
  cup_published_at timestamptz;
  entry_season_id bigint;
  entry_is_guest boolean;
  first_round_closed_at timestamptz;
  first_round_retroactive_at timestamptz;
  retroactive_operation boolean :=
    coalesce(current_setting('app.cup_retroactive_operation', true), '') = 'on';
begin
  if tg_op = 'UPDATE' then
    raise exception 'Adesoes nao podem ser alteradas; use o fluxo administrativo apropriado.'
      using errcode = '22023';
  end if;

  if tg_op = 'DELETE' then
    select cup_round.registration_closed_at, cup_round.retroactive_at,
      cup.published_at
    into first_round_closed_at, first_round_retroactive_at, cup_published_at
    from public.championship_cup_round as cup_round
    join public.championship_cup as cup on cup.id = cup_round.cup_id
    where cup_round.cup_id = old.cup_id
      and cup_round.round_id = old.first_round_id
    for update of cup_round;

    perform 1 from public.championship_round
    where id = old.first_round_id for update;

    if (
      first_round_closed_at is not null
      or exists (
        select 1 from public.championship_roundresult
        where round_id = old.first_round_id
      )
    ) and not (
      retroactive_operation
      and first_round_retroactive_at is not null
      and cup_published_at is null
    ) then
      raise exception 'Uma adesao com etapa iniciada nao pode ser removida.'
        using errcode = '22023';
    end if;

    return old;
  end if;

  select season_id, published_at into cup_season_id, cup_published_at
  from public.championship_cup where id = new.cup_id;
  select season_id, is_guest into entry_season_id, entry_is_guest
  from public.championship_driverteamseason where id = new.entry_id;
  select registration_closed_at, retroactive_at
  into first_round_closed_at, first_round_retroactive_at
  from public.championship_cup_round
  where cup_id = new.cup_id and round_id = new.first_round_id
  for update;

  if not found then
    raise exception 'A primeira etapa da adesao nao pertence a esta Copa.'
      using errcode = '22023';
  end if;

  perform 1 from public.championship_round
  where id = new.first_round_id for update;

  if cup_season_id is null or entry_season_id is null
    or cup_season_id <> entry_season_id or entry_is_guest then
    raise exception 'A Copa aceita apenas pilotos regulares do campeonato de origem.'
      using errcode = '22023';
  end if;

  if (
    first_round_closed_at is not null
    or exists (
      select 1 from public.championship_roundresult
      where round_id = new.first_round_id
    )
  ) and not (
    retroactive_operation
    and first_round_retroactive_at is not null
    and cup_published_at is null
  ) then
    raise exception 'As adesoes desta etapa ja foram encerradas.'
      using errcode = '22023';
  end if;

  new.enrolled_at := now();
  new.enrolled_by := auth.uid();
  return new;
end;
$$;

create function public.add_retroactive_cup_round(
  p_cup_id bigint,
  p_round_id bigint,
  p_cup_order smallint,
  p_entry_ids bigint[],
  p_reason text
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  caller_id uuid := auth.uid();
  cup_season_id bigint;
  cup_published_at timestamptz;
  round_season_id bigint;
  selected_count integer;
  eligible_count integer;
  normalized_reason text := btrim(p_reason);
begin
  if caller_id is null or not exists (
    select 1 from public.app_admins where user_id = caller_id
  ) then
    raise exception 'Sua conta nao possui permissao administrativa.'
      using errcode = '42501';
  end if;

  if normalized_reason is null
    or length(normalized_reason) not between 10 and 300 then
    raise exception 'Informe uma justificativa entre 10 e 300 caracteres.'
      using errcode = '22023';
  end if;

  select season_id, published_at into cup_season_id, cup_published_at
  from public.championship_cup where id = p_cup_id for update;

  if cup_season_id is null then
    raise exception 'Mini Copa nao encontrada.' using errcode = '22023';
  end if;
  if cup_published_at is not null then
    raise exception 'A inclusao retroativa so e permitida enquanto a Copa estiver em rascunho.'
      using errcode = '22023';
  end if;

  select season_id into round_season_id
  from public.championship_round where id = p_round_id for update;

  if round_season_id is null or round_season_id <> cup_season_id then
    raise exception 'A etapa deve pertencer ao campeonato oficial da Copa.'
      using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.championship_roundresult where round_id = p_round_id
  ) then
    raise exception 'Use o fluxo normal para uma etapa que ainda nao possui resultados.'
      using errcode = '22023';
  end if;

  select count(distinct selected.entry_id)::integer into selected_count
  from unnest(coalesce(p_entry_ids, array[]::bigint[])) as selected(entry_id);

  if selected_count = 0 then
    raise exception 'Selecione ao menos um piloto participante.'
      using errcode = '22023';
  end if;
  if selected_count <> cardinality(coalesce(p_entry_ids, array[]::bigint[])) then
    raise exception 'A lista de pilotos possui itens repetidos ou invalidos.'
      using errcode = '22023';
  end if;

  select count(*)::integer into eligible_count
  from public.championship_driverteamseason
  where id = any(p_entry_ids)
    and season_id = cup_season_id
    and not is_guest;

  if eligible_count <> selected_count then
    raise exception 'A Copa aceita apenas pilotos regulares do campeonato de origem.'
      using errcode = '22023';
  end if;

  if exists (
    select 1
    from public.championship_cup_entry as cup_entry
    join public.championship_cup_round as first_round
      on first_round.cup_id = cup_entry.cup_id
      and first_round.round_id = cup_entry.first_round_id
    where cup_entry.cup_id = p_cup_id
      and cup_entry.entry_id = any(p_entry_ids)
      and (
        first_round.cup_order < p_cup_order
        or first_round.registration_closed_at is not null
        or exists (
          select 1 from public.championship_roundresult as result
          where result.round_id = first_round.round_id
        )
      )
  ) then
    raise exception 'Um piloto selecionado ja possui participacao consolidada em uma etapa anterior.'
      using errcode = '22023';
  end if;

  perform set_config('app.cup_retroactive_operation', 'on', true);

  insert into public.championship_cup_round (
    cup_id,
    round_id,
    cup_order,
    registration_closed_at,
    retroactive_at,
    retroactive_by,
    retroactive_reason
  ) values (
    p_cup_id,
    p_round_id,
    p_cup_order,
    now(),
    now(),
    caller_id,
    normalized_reason
  );

  delete from public.championship_cup_entry
  where cup_id = p_cup_id and entry_id = any(p_entry_ids);

  insert into public.championship_cup_entry (
    cup_id,
    entry_id,
    first_round_id,
    enrolled_by
  )
  select p_cup_id, selected.entry_id, p_round_id, caller_id
  from unnest(p_entry_ids) as selected(entry_id);

  insert into public.championship_cup_audit (
    cup_id,
    round_id,
    action,
    reason,
    actor_id,
    details
  ) values (
    p_cup_id,
    p_round_id,
    'RETROACTIVE_ROUND_ADDED',
    normalized_reason,
    caller_id,
    jsonb_build_object(
      'cup_order', p_cup_order,
      'entry_ids', to_jsonb(p_entry_ids)
    )
  );
end;
$$;

create function public.undo_retroactive_cup_round(
  p_cup_id bigint,
  p_round_id bigint,
  p_reason text
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  caller_id uuid := auth.uid();
  cup_published_at timestamptz;
  original_reason text;
  removed_entry_ids bigint[];
  normalized_reason text := btrim(p_reason);
begin
  if caller_id is null or not exists (
    select 1 from public.app_admins where user_id = caller_id
  ) then
    raise exception 'Sua conta nao possui permissao administrativa.'
      using errcode = '42501';
  end if;

  if normalized_reason is null
    or length(normalized_reason) not between 10 and 300 then
    raise exception 'Informe uma justificativa entre 10 e 300 caracteres.'
      using errcode = '22023';
  end if;

  select cup.published_at, cup_round.retroactive_reason
  into cup_published_at, original_reason
  from public.championship_cup_round as cup_round
  join public.championship_cup as cup on cup.id = cup_round.cup_id
  where cup_round.cup_id = p_cup_id
    and cup_round.round_id = p_round_id
  for update of cup_round, cup;

  if not found or original_reason is null then
    raise exception 'Inclusao retroativa nao encontrada.' using errcode = '22023';
  end if;
  if cup_published_at is not null then
    raise exception 'Uma inclusao retroativa publicada nao pode ser desfeita por este fluxo.'
      using errcode = '22023';
  end if;

  select coalesce(array_agg(entry_id order by entry_id), array[]::bigint[])
  into removed_entry_ids
  from public.championship_cup_entry
  where cup_id = p_cup_id and first_round_id = p_round_id;

  perform set_config('app.cup_retroactive_operation', 'on', true);

  delete from public.championship_cup_entry
  where cup_id = p_cup_id and first_round_id = p_round_id;

  delete from public.championship_cup_round
  where cup_id = p_cup_id and round_id = p_round_id;

  insert into public.championship_cup_audit (
    cup_id,
    round_id,
    action,
    reason,
    actor_id,
    details
  ) values (
    p_cup_id,
    p_round_id,
    'RETROACTIVE_ROUND_REMOVED',
    normalized_reason,
    caller_id,
    jsonb_build_object(
      'original_reason', original_reason,
      'removed_entry_ids', to_jsonb(removed_entry_ids)
    )
  );
end;
$$;

revoke all on function public.add_retroactive_cup_round(bigint, bigint, smallint, bigint[], text)
  from public, anon;
revoke all on function public.undo_retroactive_cup_round(bigint, bigint, text)
  from public, anon;
grant execute on function public.add_retroactive_cup_round(bigint, bigint, smallint, bigint[], text)
  to authenticated, service_role;
grant execute on function public.undo_retroactive_cup_round(bigint, bigint, text)
  to authenticated, service_role;

notify pgrst, 'reload schema';

commit;
